database:
 type: DB
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  application:
    name: EnjoyMD
  datasource:
    url: jdbc:postgresql://localhost:5432/EnjoyMD
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        type: trace
    show-sql: true
    generate-ddl: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: TRACE
upload:
  path: D:/post-img